
# This configuration file is part of Supabase Edge Functions
project_id = ""

[gcr]
disable_public_cache = true

[deploy.release]
include = ["**"]
exclude = ["node_modules/**", "**/node_modules/**", "**/__pycache__/**", "*.ts", "!*.d.ts"]

[migrations]
include = ["**"]
exclude = ["node_modules/**", "**/node_modules/**", "**/__pycache__/**", "*.ts", "!*.d.ts"]

[environment_variables]
GEMINI_API_KEY = ""
